# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4600daf4b6fd8f09ba3593b352808fb625ada68a4658059a5ec34274dee50b4aefbed5132226476e52de4cf621f10e6d92fd538b27f302a40d2a8c47a130d5d2

test:
  secret_key_base: d1aa3df4d6a5534de7fd68e4a288adbb3f1d9e690713bc2285b14b1345041b69abe9b0d40c86d8d7c59b9d33d457737b589a555e5923f76e4fc81c91bc48cb94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
